git-rpublish: Robustness: Specify the current branch name so that a publish overrides an existing push configuration
A branch might have been (inadvertently) changed to track a different branch. Then a publish would not do the expected thing, but instead push to the previous push configuration:
> $ git opublish pushtest
> To github.com:inkarkat/test.git
>  ! [rejected]        pushtest -> lala (non-fast-forward)
> error: failed to push some refs to 'github.com:inkarkat/test.git'
> hint: Updates were rejected because a pushed branch tip is behind its remote
> hint: counterpart. Check out this branch and integrate the remote changes
> hint: (e.g. 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.