FIX: Regression: selectedgcommit-command invocations cause error
> fatal: ambiguous argument 'commitlike': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> ERROR: No commits available.

Need to use ... -2 GIT-COMMAND COMMITS now.