git-showfiles: FIX: Regression: Typo: Wrong variable used (after 087c6050)
> $ git-selectedcommit-command -4 blamesamefiles --revisions COMMITS \; --max-count 4
> 1) seventh (inkarkat/test3@e890dd7 continued)
> 2) more changes on a stacked branch
> 3) even more unrelated changes
> 4) fourth (25c21de continued)
> #? 1.
> ERROR: --revisions must be concluded with ''

(This corrects commit 087c6050cdbb1ee1d4b0948f4f8ba33c10f32921)

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)