Robustness: CHG: reintegrateto now returns 99 if already on master, supersubreintegratetom continues then
When there are problems with GitHub Action execution (jobs not getting picked up by a runner), the reintegration aborts:
> Waiting for the GitHub action to validate the build on the branch before pushing.
> 20:03: The fast-forward-integrated branch build did not become completed and a success: queued  7 minutes ago     https://github.com/ResilientGroup/ReBuild/actions/runs/9174077720.
> Push preparation failed.

But it's then not possible to re-run, because submodules have been fast-forwarded to master:
> Checking for unintegrated submodules... No such submodules found.
> All 17 submodules have been reintegrated already; now integrating the superproject.
> Apparently the submodule fast-forward-integration was interrupted after the superproject had been fast-forward-integrated but the submodules are still on the fast-forward-integrated source branch.
> Assuming you've fixed the problem, updated and pushed all branches, shall I fast-forward the 17 submodule into main now, wait for the GitHub action, and then push the branches quasi-transactionally? ([O]k / [C]ancel)? o
>
> XxXxxxx:
>
> Fast-forwarding submodule into master:
> XxxxxXxxxXxxxxx:
> ERROR: Cannot reintegrate master onto itself; check out a different branch first.

Make git-reintegrateto exit with 99 in that case and turn the error message into a note. I rationalize that this is more of a "wrong context to invoke this in" problem than wrong command-line arguments supplied.
Make git-supersubreintegratetom accept an all-99 exit meaning that all submodules already are on master.