Introduce git-rdeletebr wrapper that offers suppression of error when remote branch doesn't exist
> error: unable to delete 'foo': remote ref does not exist
> error: failed to push some refs to '...'