git-stash-pop-to-dirty: Add --3way so we get conflict markers instead of discarding the entire patch
And --index as that's implied by --3way, but I'd rather be explicit.
Without it, we just get an error:
> error: patch failed: README.md:16
> error: README.md: patch does not apply

System-info: Armbian 24.11.1 noble, aarch64
Platform-info: git version 2.47.0, hub version 2.14.2, gh version 2.62.0 (2024-11-14), git-lfs/3.5.1 (GitHub; linux arm64; go 1.21.8)