git-rtagtype: BUG: Regression: --sort-by-age still complains about missing corresponding tag (after 560784bd)
I reimplemented this because the chosen sorting may mess with the default order where the annotated dereferenced ^{} comes immediately after the tag itself, but somehow still added a sanity check for the ordering. This fails when sorting by age:
> ERROR: Annotated dereferenced tag refs/tags/v2.1.0^{} without a corresponding tag.

Drop the check and assume that eventually everything has been seen and matches. As we don't iterate over the annotated dict, nothing bad happens even if lonely dereferenced commits were encountered.

(This corrects commit 560784bd1460a8c41c709908b63b4b64c153b6b8)

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.48.1, hub version 2.14.2, gh version 2.55.0 (2024-08-20), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)