git-do-extensions: FIX: Regression: "src -- dirty-sh" broken
My custom commands use DIR -- "$@", if the latter is -- dirty-sh, the extension command isn't parsed any longer, and git-wcdo complains:
> git: 'dirty-sh' is not a git command. See 'git --help'.
I also cannot remove the --, as then there's no separation between the last DIR and the dirty-sh:
> ERROR: Not a directory: dirty-sh

This seems to work:
- Two trailing -- drop the second one.
- When the next argument is an option (-f|--foo), continue parsing so that stuff like --dirty gets translated.
- When the next argument isn't an option, break so that extension commands like dirty-sh get translated.