git-subcobr: FIX: Use "submodule update --checkout SUBMODULE" instead of "checkout HEAD -- SUBMODULE"
The latter should be equivalent, but corrupts a separate worktree checkout of the submodule (via git-worktree-with-submodules-add).

> $ git co -- test2
> fatal: not a git repository: ../../test/.git/worktrees/test.dev/modules/test2
> error: Submodule 'test2' could not be updated.
> $ git
> fatal: not a git repository: test2/../../test/.git/worktrees/test.dev/modules/test2
> $ c test2 m .git
> gitdir: ../../test/.git/worktrees/test.dev/modules/test2
> $ c test2 v .git
> $ c test2 m .git
> gitdir: ../../test/.git/modules/test2/worktrees/test2

(cherry picked from commit c5aa335b2c20c29a08784d77becdfb4bb7eb5caa)