git-selectedcommit-command: BUG: Need to fall back to HEAD
In commitSource()'s DWIM case, R2 may be empty, but "git log ^R1^@ R2" requires that both arguments are non-empty:
> $ git-selectedcommit-command --single-only -2 detach COMMITS '3a7d6ac11e29c4b18a65b0f01cf98cb793d6c687^^..'
> fatal: ambiguous argument '': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> ERROR: No commits available.
Just default to HEAD.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.88.0 (2026-03-10), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)