Robustness: Detect failure to revert the index changes and show necessary manual changes
This can happen when the changes to index and working copy overlap:
    $ echo first change >> file
    $ git addu
    $ echo second change >> file
    $ git stashi
    ERROR: The following reversals of the index failed and need to be applied manually (in reverse!):
    diff a/file b/file    (rejected hunks)
    @@ -1,3 +1,4 @@ it is good
    +first change

Obtain the changes via "git apply --reject", show them, and remove then already (presumably, only small changes would be applied manually, anyway; in case of huge conflicts the user would rather undo and choose a different approach), so that they don't pollute the working copy.