git-{[o]archive{last,br},tag-version}: Only push the created tags to origin (after 8a3e3f8)
To avoid rejected errors on other tags that may reference different commits locally.

>  * [new tag]         archive/refactoring2 -> archive/refactoring2
>  ! [rejected]        1.2.7 -> 1.2.7 (already exists)
>  ! [rejected]        1.2.8 -> 1.2.8 (already exists)
>  ! [rejected]        1.2.9 -> 1.2.9 (already exists)
> error: failed to push some refs to '...'

(This relates to commit 8a3e3f81ca98fd1d8b95193055ab2d711a0c7914)