Generalization: Extract git-out through new custom-range.sh br-variant type
Though identical in the optional -b|--branch branch parameter, the implementation relies on a custom rev-range-* command. It's too complex to add that variation into branch-range.sh, so rather clone it into a separate custom-range.sh
For the special implementation of "outbase", we can use the wrapper's sub-sub-command override and provide git-out-base.

FIX: out{base,pred}{lg,s} never worked; need to handle --no-range in git-rev-range-outgoing.
> ERROR: --end-revision cannot be combined with --no-range!