branch-range: Debugging: FIX: Avoid merge-base error on EXEC=echotract during debugging (0ac88c08 continued)
> $ EXEC=echotrace git bm changesetfilesminesthere
> + git-branch-command --keep-position master-command --keep-position rev-range --revision MASTER --end-revision BRANCH --with-range \  -2 echo RANGE
> ERROR: Cannot find merge base with master.

(This continues commit 0ac88c08c61cfc34b282ccb93dbb4e0d7f6a07b9)

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.96.0 (2026-07-02), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)