git-checkoutrevisionselected: BUG: Need to turn $rev into $rev^ for git-showfiles when --previous is passed
The offered selection of files also needs to consider that we're targeting the revision prior to the passed one.
Without that, the set of files is off and may lead to errors such as (when the commit adds a new file and we want to checkout its prior commit):
> error: pathspec 'news.txt' did not match any file(s) known to git

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: git version 2.50.1, hub version 2.14.2, gh version 2.95.0 (2026-06-17), git-lfs/3.6.1 (GitHub; linux amd64; go 1.23.3)