git-testcommit: BUG: Cannot commit new files
Because we're circumventing the index.
> error: pathspec 'new.txt' did not match any file(s) known to git
Separate existing and non-existing files, and amend the latter through git-commituntracked.
The command will still fail for existing untracked files, but that's okay.